--- #YAML:1.0
name:               Net-Daemon
version:            0.44
abstract:           Perl extension for portable daemons
author:
    - Jochen Wiedmann <joe@ispsoft.de>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    File::Basename:  0
    Getopt::Long:    0
    IO::Socket:      0
    Symbol:          0
resources:
    homepage:    http://wiki.github.com/toddr/Net-Daemon
    license:     http://dev.perl.org/licenses/
    repository:  http://github.com/toddr/Net-Daemon
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
